# Generated by Django 5.1.4 on 2024-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastPlatechecked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=6)),
                ('plate', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Last Plate checked',
            },
        ),
        migrations.CreateModel(
            name='LastPlateIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=6)),
                ('plate', models.CharField(max_length=6)),
                ('issued', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Last Plate Issued',
            },
        ),
        migrations.CreateModel(
            name='UncheckedPlates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=6)),
            ],
        ),
    ]
