# Generated by Django 5.1.4 on 2025-01-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lastplateissued_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecheckForAPKPlates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=6)),
            ],
        ),
    ]
