# Generated by Django 5.1.4 on 2025-01-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recheckforapkplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheckforapkplates',
            name='apk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recheckforapkplates',
            name='first_reg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recheckforapkplates',
            name='vehicle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
