# Generated by Django 5.1.4 on 2025-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recheckforapkplates_apk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheckforapkplates',
            name='checked_apk',
            field=models.DateField(blank=True, null=True),
        ),
    ]
