# Generated by Django 5.1.4 on 2024-12-21 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('type_code', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('raw_make', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('code', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('raw_model', models.CharField(blank=True, max_length=256, null=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='vehicles.make')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(max_length=256, null=True)),
                ('licence_plate', models.CharField(db_index=True, max_length=8, unique=True)),
                ('raw_name', models.CharField(blank=True, max_length=256, null=True)),
                ('first_reg', models.DateField(blank=True, null=True)),
                ('first_reg_in_NL', models.DateField(blank=True, null=True)),
                ('imported_in_NL', models.DateField(blank=True, null=True)),
                ('apk', models.DateField(blank=True, null=True)),
                ('valid_apk', models.BooleanField(default=True)),
                ('insurance', models.BooleanField(default=True)),
                ('exported', models.BooleanField(db_index=True, default=False)),
                ('engine_volume', models.CharField(max_length=9)),
                ('cylinder_count', models.CharField(max_length=2)),
                ('curb_weight', models.CharField(blank=True, max_length=10, null=True)),
                ('empty_weight', models.CharField(blank=True, max_length=10, null=True)),
                ('max_weight_tech', models.CharField(blank=True, max_length=10, null=True)),
                ('max_weight_legal', models.CharField(blank=True, max_length=10, null=True)),
                ('gross_combination_weight', models.CharField(blank=True, max_length=10, null=True)),
                ('trailer_with_brakes', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('trailer_without_brakes', models.CharField(blank=True, max_length=10, null=True)),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_type', to='vehicles.bodytype')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='vehicles.color')),
                ('fuel_type', models.ManyToManyField(to='vehicles.fueltype')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehicles.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehicles.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='make',
            name='vahicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclecategory'),
        ),
    ]
