# Generated by Django 5.1.4 on 2024-12-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='vahicle_category',
            new_name='vehicle_category',
        ),
    ]
