# Generated by Django 5.1.4 on 2024-12-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_vahicle_category_make_vehicle_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={'verbose_name_plural': 'Vehicle Categories'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclecategory'),
        ),
    ]
