# Generated by Django 5.1.4 on 2024-12-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_engine_volume_alter_vehicle_hp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodytype',
            old_name='type_code',
            new_name='code',
        ),
    ]
