# Generated by Django 5.1.4 on 2024-12-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_curb_weight_alter_vehicle_empty_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cylinder_count',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_volume',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
