# Generated by Django 5.1.4 on 2024-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicle_cylinder_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='hp2',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='kw2',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
