# Generated by Django 5.1.4 on 2024-12-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_hp2_vehicle_kw2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
    ]
