# Generated by Django 5.1.4 on 2024-12-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_vehicle_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
