# Generated by Django 5.1.4 on 2025-01-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_vehiclecategory_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
