# Generated by Django 5.1.4 on 2025-01-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_vehicle_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='first_reg',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
